# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 379)
        self.Form = QtWidgets.QWidget(MainWindow)
        self.Form.setObjectName("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Form)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtFtpUrl = QtWidgets.QLineEdit(self.Form)
        self.txtFtpUrl.setObjectName("txtFtpUrl")
        self.horizontalLayout.addWidget(self.txtFtpUrl)
        self.btnOpen = QtWidgets.QPushButton(self.Form)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lstFileList = QtWidgets.QListWidget(self.Form)
        self.lstFileList.setObjectName("lstFileList")
        self.verticalLayout.addWidget(self.lstFileList)
        MainWindow.setCentralWidget(self.Form)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Site_List = QtWidgets.QAction(MainWindow)
        self.action_Site_List.setObjectName("action_Site_List")
        self.action_Recent_Sites = QtWidgets.QAction(MainWindow)
        self.action_Recent_Sites.setObjectName("action_Recent_Sites")
        self.action_Content = QtWidgets.QAction(MainWindow)
        self.action_Content.setObjectName("action_Content")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menu_File.addAction(self.action_Site_List)
        self.menu_File.addAction(self.action_Recent_Sites)
        self.menuHelp.addAction(self.action_Content)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QFTP"))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.menu_File.setTitle(_translate("MainWindow", "&Sites"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.action_Site_List.setText(_translate("MainWindow", "&Site List..."))
        self.action_Recent_Sites.setText(_translate("MainWindow", "&Recent Sites..."))
        self.action_Content.setText(_translate("MainWindow", "&Content"))
        self.action_Content.setShortcut(_translate("MainWindow", "F1"))
        self.action_About.setText(_translate("MainWindow", "&About..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
